### ISSUE TITLE
Assign rule regex seems incorrect

### ISSUE THREAD

**Issue by zachfi** [voxpupuli/puppet-icinga2#209]
Hi.  I'm starting to migrate to this module, and I'm trying to apply a service that looks like the following.

```
  icinga2::object::notification { 'slack-host':
    command      => 'slack-host-notification',
    users        => ['Ops'],
    apply        => true,
    apply_target => 'Host',
    assign       => ['host.vars.os'],
    interval     => 86400,
  }
```

The assign target fails with the following error:

```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Function Call, validate_re(): "host.vars.os" does not match "^.+\\s+(=>\\s+.+\\s+)?in\\s+.+$" at /usr/local/etc/puppet/code/environments/newmon/modules/icinga2/manifests/object.pp:91:28 at /usr/local/etc/puppet/code/environments/newmon/modules/icinga2/manifests/object/service.pp:266 on node mon5.example.com
```

From my reading of the docs, and prior working with icinga2, the assign rule above should be valid.  My goal is to assign this notification to a host where the os variable exists, no matter its value.  Perhaps there is a better approach to this.  Not all hosts have the os variable, since I might be monitoring external systems that don't run puppet, for example.

Is there a simple workaround, or does the regex need updating?  Any advice here would be appreciated.

**Comment by zachfi** [comment]
I just noticed #208, which looks related, but #208 looks like the regex at least passes.  Maybe I'm doing something wrong.

**Comment by Reamer** [comment]
I do something quite similar and it works for me with module v1.0.1.
My definition in hiera looks nearly the same:
my running configuration:
```
  mattermost_host:
    target: '/etc/icinga2/conf.d/notifications_apply.conf'
    apply: true
    apply_target: Host
    assign:
      - 'true'
    command: 'mattermost_host'
    states: [ 'Up', 'Down' ]
    types: [ 'Problem', 'Acknowledgement', 'Recovery', 'Custom', 'FlappingStart', 'FlappingEnd', 'DowntimeStart', 'DowntimeEnd', 'DowntimeRemoved' ]
    period: '24x7'
    users: [ 'mattermost' ]
```

But I also test with 'host.vars.os' and it works, no regex problems.
```
  mattermost_host:
    target: '/etc/icinga2/conf.d/notifications_apply.conf'
    apply: true
    apply_target: Host
    assign:
      - 'host.vars.os'
    command: 'mattermost_host'
    states: [ 'Up', 'Down' ]
    types: [ 'Problem', 'Acknowledgement', 'Recovery', 'Custom', 'FlappingStart', 'FlappingEnd', 'DowntimeStart', 'DowntimeEnd', 'DowntimeRemoved' ]
    period: '24x7'
    users: [ 'mattermost' ]
```

Best Regards
Reamer
