### ISSUE TITLE
assign/ignore in static array does not work.

### ISSUE THREAD

**Issue by jkroepke** [voxpupuli/puppet-icinga2#221]
Hi,

it looks like assign rules with an in operator w/ a static array does not work:

```
  mail_service:
    apply: true
    assign: ['notification in host.groups']
    apply_target: Service
    ignore: ['service.check_command in [check_mem_by_ssh, check_iostat_by_ssh, check_apt_by_ssh, check_cpu_by_ssh, check_procs_by_ssh, check_puppet_agent_by_ssh]']
    user_groups: ['admins']
    import: ['mail-service-notification']
```

results in

```
apply Notification "mail_service" to Service {
   import "mail-service-notification"

  user_groups = [ "admins", ]
  interval = 43200
  assign where "notification" in host.groups
  ignore where service.check_command in "[check_mem_by_ssh, check_iostat_by_ssh, check_apt_by_ssh, check_cpu_by_ssh, check_procs_by_ssh, check_puppet_agent_by_ssh]"
}
```

but I expect this:

```
apply Notification "mail_service" to Service {
   import "mail-service-notification"

  user_groups = [ "admins", ]
  interval = 43200
  assign where "notification" in host.groups
  ignore where service.check_command in ["check_mem_by_ssh", "check_iostat_by_ssh", "check_apt_by_ssh", "check_cpu_by_ssh", "check_procs_by_ssh", "check_puppet_agent_by_ssh"]
}
```
