### ISSUE TITLE
Hiera advice for zone/endpoint/hosts needed, for independent DCs

### ISSUE THREAD

**Issue by linuxmail** [voxpupuli/puppet-icinga2#298]
Hello,

I need an advice for integrating zones/endpoints and hosts for Icinga2 agents and non-agent hosts for **independent** datacenters.

We have at office a central Icinga2 master running which is managed via Puppet. I have to add satellites, agents and non-agent (snmp) hosts which are managed through a different Puppet server. In that way, I have to add the zones/endpoints and hosts manually instead of auto creating via exported resources.
At this time, I have a running setup with:

**hiera.yaml:**
```
:hierarchy:
  - "node/%{::fqdn}"
  - "domain/%{::domain}"
  - "role/%{::role}"
  - "profile/%{calling_class_path}"
  - "operatingsystem/%{::operatingsystem}/%{::operatingsystemmajrelease}"
  - "operatingsystem/%{::operatingsystem}"
  - "osfamily/%{::osfamily}"
  - "datacenter/%{::datacenter}"
  - "virtual/%{::is_virtual}"
  - common
  - monitoring
  - global
```

**hieradata/role/mon.yaml**
```
---
classes:
  - role::icinga2_server
...
icinga2::feature::api::endpoints:
  "%{::fqdn}": {}
  'satellite.dmz1.example.com':
    host: "%{::fqdn}"
    target: '/etc/icinga2/zones.d/satellite.dmz1.example.com/satellite.dmz1.example.com.conf'
  'foo.example.com':
    host: 192.168.14.5
    target: '/etc/icinga2/zones.d/satellite.dmz1.example.com/foo.example.com.conf'

icinga2::feature::api::zones:
  master:
    endpoints:
      - "%{::fqdn}"
  satellite.dmz1.example.com:
    endpoints:
      - 'satellite.dmz1.example.com'
    parent: 'master'
    target: '/etc/icinga2/zones.d/satellite.dmz1.example.com/satellite.dmz1.example.com.conf'
  foo.example.com:
    endpoints:
      - 'foo.example.com'
    parent: 'satellite.dmz1.example.com'
    target: '/etc/icinga2/zones.d/satellite.dmz1.example.com/foo.example.com.conf'
...
```
The hosts and directory is a classical manifests

**modules/profile/manifests/icinga2/satellite.pp:**
```

class profile::icinga2::satellite::dmz1(

  $zone = 'satellite.dmz1.example.com''

)
{

  # Zone directories
  file { [ "/etc/icinga2/zones.d/$zone", ]:
    ensure =>  directory,
    owner =>  'nagios',
    group =>  'nagios',
    mode =>  '0750',
    tag =>  'icinga2::config::file',
  }~>

icinga2::object::host { 'satellite.dmz1.example.com':
    display_name  => 'satellite.dmz1.example.com',
 vars          => {
      'client_endpoint'      => 'satellite.dmz1.example.com',
},
...
 target        => "/etc/icinga2/zones.d/${zone}/satellite.dmz1.example.com.conf",
  }

...

  icinga2::object::host { 'foo.example.com':
    display_name  => 'foo.example.com',
    address       => '192.168.14.5',
    check_command => 'hostalive',
    zone        => 'satellite.dmz1.example.com',
...
}
```

As you can see, it looks very awful, but it works. Everything which uses the PuppetDB (all at the office network) is fine, but integrating other zones is much harder, as you have to know, where to find the right files.

I try to use much as I can Hiera for objects/values which are changed often. I use the following constellation: 

- profile  -> Icinga2 master, icingaweb2... plugins ... and the profile::icinga2::satellite::dmz1
- role -> Assign all needed profiles to the role "mon"
- node -> Added hosts, which has no Icinga agent (icinga2::object::host:) (mostly snmp devices at the office network)

I need an advice for putting all zones/endpoints/hosts into separated hiera file, which are called on the Icinga master via the Puppet agent.
The hieradata/role file is not the right place I think and also the hieradata/node/<::fqdn> isn't the best choice too. 

Maybe some others had the same constellation and it would be great to hear from other solutions, just to get an idea, how to manage a lot of zones/endpoints with all there parents in a clear structure. 

Ma I should create new profiles:

- class profile::icinga2::satellite::endpoints
- class profile::icinga2::satellite::zones
- class profile::icinga2::satellite::hosts

but where to put the hiera file .... ?  Maybe the profile/%{calling_class_path} is an idea ...

cu denny
