### ISSUE TITLE
Only last empty hash is stored

### ISSUE THREAD

**Issue by linuxmail** [voxpupuli/puppet-icinga2#308]
Hello,

I try create a host template for the mysql_health_check ... and I have problems to get a syntax like:
```
vars.check["foo"] = {} 
vars.check["bar"] = {}
....
```
With the following code:
```
  @@icinga2::object::host { 'mysql-database':
    template      => true,
    check_command => 'mysql',
    vars          => {
        'mysql_health'       => {
         'bufferpool-hitrate'  => { },
         'bufferpool-wait-free'  => { },
      },
...
}
```
The last line wins.

I have a similar config for my interfaces or blockdevices, but thy exists in my hiera YAML config and I get the correct output:

```
  vars.blockdevices["sda"] = {
    path = "/dev/sda"
    iostats_disk = "sda"
  }
  vars.blockdevices["sdb"] = {
    path = "/dev/sdb"
    iostats_disk = "sdb"
  }
```
My Yaml
```
icinga2::host:
  vars:
    blockdevices:
      'sda':
        'path': '/dev/sda'
        'iostats_disk': 'sda'
      'sdb':
        'path': '/dev/sdb'
        'iostats_disk': 'sdb'
```

So it looks like, that my Puppet syntax is wrong. Can someone point me in the right direction ?

cu denny
