### ISSUE TITLE
Allow to get attributes from function result

### ISSUE THREAD

**Issue by zehweh** [voxpupuli/puppet-icinga2#586]
Currently, only hashes are allowed for `argument` in the `checkcommand` object.
To be able to use functions to copy `arguments` from other `checkcommand`s, strings need to be allowed.

Example usecase:
`my-disk` checkcommand which is based on the original `disk` checkcommand (only difference: sudo):

Hiera:
```
  'icinga2::object::checkcommand':
    my-disk:
      command:
        - sudo
        - PluginDir + /check_disk
      arguments: get_check_command("disk").arguments
```

## Expected Behavior
```
object CheckCommand "my-disk" {
  import "plugin-check-command"

  command = [ "sudo", PluginDir + "/check_disk", ]
  arguments = get_check_command("disk").arguments
}
```

## Current Behavior
`Evaluation Error: Error while evaluating a Resource Statement, Icinga2::Object::Checkcommand[my-disk]: parameter 'arguments' expects a value of type Undef or Hash, got String`

## Your Environment
* Module version (`puppet module list`): icinga-icinga2 (v2.3.0)
* Puppet version (`puppet -V`): 6.7.2
* Operating System and version: Ubuntu 18.04.1 LTS

**Comment by lbetz** [comment]
We write a simple parser. So the parser isn't able to handle such complex values depend on functions. Changing the type of arguments to hash or string results

arguments = get_check_command("disk).arguments"

This case is not easy to add to our parser, please use an static config file as file resource with a tag to icinga2::config::file.

**Comment by lbetz** [comment]
Problem is at the moment methods like .arguments are not supported.

**Comment by lbetz** [comment]
But it seems to be simple to implement. Try out branch 'enhancement/allow-to-get-attributes-from-function-result'.

**Comment by zehweh** [comment]
Thanks for your quick response.

Running your branch with:
```
    my_disk:
      command:
        - sudo
        - PluginDir + /check_disk
      arguments: get_check_command(disk).arguments
```

still results in 
`arguments = get_check_command("disk).arguments"`

I have to disable the parser like this:
`arguments: '-:get_check_command("disk").arguments'`

to get the correct config:
`arguments = get_check_command("disk").arguments`
