### ISSUE TITLE
How to add custom variables to a template?

### ISSUE THREAD

**Issue by Napsty** [voxpupuli/puppet-icinga2#710]
## Context

Icinga2 supports the definition of custom variables in the templates, for example host templates. These custom vars are then automatically applied on all the Hosts using this host template.

```
template Host "generic-host" {
  check_command = "hostalive_4"
  max_check_attempts = 3
  check_interval = 1m
  retry_interval = 30s
  vars.custom_var = "Feuerstein"
}
```

But how can this be added with the Puppet module?

## Expected Behavior
Adding the custom variable to the host template "generic-host", configured in Puppet:

```
profile::icinga2master::icinga2_object_host:
  generic-host:
    check_command: hostalive_4
    check_interval: 1m
    max_check_attempts: 3
    retry_interval: 30s
    vars.custom_var: 'Feuerstein'
    target: /etc/icinga2/conf.d/templates.conf
    template: true
```

Results in the following template in the final config file (/etc/icinga2/conf.d/templates.conf):

```
template Host "generic-host" {
  check_command = "hostalive_4"
  max_check_attempts = 3
  check_interval = 1m
  retry_interval = 30s
  vars.custom_var = "Feuerstein"
}
```

## Current Behavior
Puppet run falls on its nose, stating that:

```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Icinga2::Object::Host[generic-host]: has no parameter named 'vars.custom_var' (file: /etc/puppetlabs/code/environments/production/site/profile/manifests/icinga2master.pp, line: 35) on node icinga2
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```

I also tried it with `vars.custom_var: '-:Feuerstein'` but same error.

## Your Environment
* Module version (`puppet module list`): icinga-icinga2 (v3.3.1)
* Puppet version (`puppet -V`): 7.19.0
* Operating System and version: Ubuntu 22.04

Thanks for any hints.

**Comment by lbetz** [comment]
Hi Claudio,

vars has to be a hash. So your yaml code must look like that:
```
profile::icinga2master::icinga2_object_host:
  generic-host:
    check_command: hostalive_4
    check_interval: 1m
    max_check_attempts: 3
    retry_interval: 30s
    vars
      custom_var: Feuerstein
    target: /etc/icinga2/conf.d/templates.conf
    template: true
```
